# Ubuntu
# https://www.ubuntu.com/
# v16.04

# base image: ubuntu:16.04
FROM ubuntu:16.04

# File Author / Maintainer
MAINTAINER Frederic Lemoine <frederic.lemoine@pasteur.fr>

RUN mkdir /pasteur

ENTRYPOINT ["/bin/bash"]
