# perl
# https://www.perl.org
# v5.26.1

# base image: perl:5.26.1
FROM perl:5.26.1

# File Author / Maintainer
MAINTAINER Frederic Lemoine <frederic.lemoine@pasteur.fr>

RUN mkdir /pasteur

ENTRYPOINT ["/usr/local/bin/perl"]
