# SRA Tools
# https://github.com/ncbi/sra-tools
# v3.0.1

# base image: Ubuntu
FROM ncbi/sra-tools:3.0.1

# File Author / Maintainer
LABEL maintainer="frederic.lemoine@pasteur.fr"

RUN apk add bash

ENTRYPOINT ["fasterq-dump"]
