# T-Coffee
# https://github.com/cbcrg/tcoffee/tree/18778a82eb1300cc567d326e7b67eeb647244434
#  Version_13.46.2.7c9e712d

# base image: Ubuntu
FROM cbcrg/tcoffee:Version_13.46.2.7c9e712d

# File Author / Maintainer
LABEL maintainer="frederic.lemoine@pasteur.fr"

RUN mkdir /pasteur

ENTRYPOINT ["/opt/tcoffee/bin/t_coffee"]
