#!/usr/bin/env bash

RAXMLNG=/usr/local/bin/raxml-ng
MAD=/usr/local/bin/mad
BOOSTER=/usr/local/bin/booster

TREE=$1
shift;

MODEL=/usr/local/bin/full_model_raxml

case $TREE in
    raxml)
	MODEL=/usr/local/bin/full_model_raxml
	echo $MODEL
	;;
    iqtree)
	MODEL=/usr/local/bin/full_model_iqtree
	echo $MODEL
	;;
    fasttree)
	MODEL=/usr/local/bin/full_model_fasttree
	echo $MODEL
	;;
    *)
	MODEL=/usr/local/bin/full_model_raxml
	echo $MODEL
    ;;
esac

PYTHONPATH=/usr/local/bootstrap_repo python3 /usr/local/bootstrap_repo/user_code/predict_branch_supports.py --raxml_ng_path $RAXMLNG --mad_path $MAD --booster_path $BOOSTER --trained_ML_model_path $MODEL $@
