name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - biopython=1.78
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - conda=23.3.1
  - conda-package-handling
  - conda-package-streaming
  - cryptography=40.0.1
  - et_xmlfile=1.1.0
  - fmt=9.1.0
  - icu=72.1
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.0
  - krb5=1.20.1
  - libarchive=3.6.2
  - libcurl=7.88.1
  - libcxx=16.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.4.1
  - libmambapy=1.4.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.1
  - matplotlib
  - ncurses=6.3
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openpyxl=3.0.10
  - openssl=3.1.0
  - packaging=23.0
  - pandas=1.5.3
  - pip=23.0.1
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.11.2
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.7
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=67.6.1
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.40.0
  - xz=5.2.6
  - yaml-cpp=0.7.0
  - zstandard=0.19.0
  - zstd=1.5.2
