# MultiQC
# http://multiqc.info/
# v1.4

# base image: Ubuntu
FROM ewels/multiqc:v1.4

# File Author / Maintainer
MAINTAINER Frederic Lemoine <frederic.lemoine@pasteur.fr>

RUN mkdir /pasteur

ENTRYPOINT ["/usr/local/bin/multiqc"]
