# MultiQC
# http://multiqc.info/
# v1.10

# base image: Ubuntu
FROM ewels/multiqc:1.10

# File Author / Maintainer
LABEL maintainer=frederic.lemoine@pasteur.fr

RUN mkdir /pasteur

ENTRYPOINT ["/usr/local/bin/multiqc"]
