# MultiQC
# http://multiqc.info/
# v1.9

# base image: Ubuntu
FROM ewels/multiqc:1.9

# File Author / Maintainer
MAINTAINER Frederic Lemoine <frederic.lemoine@pasteur.fr>

RUN mkdir /pasteur

ENTRYPOINT ["/usr/local/bin/multiqc"]
