# Guppy
# 
# v3.1.5

# base image: genomicpariscentre/guppy:3.1.5
FROM genomicpariscentre/guppy:3.1.5

# File Author / Maintainer
MAINTAINER Frederic Lemoine <frederic.lemoine@pasteur.fr>

RUN mkdir /pasteur

ENTRYPOINT ["guppy_basecaller"]
