# T-Coffee
# https://github.com/cbcrg/tcoffee/tree/18778a82eb1300cc567d326e7b67eeb647244434
# Version_11.00.18778a8

# base image: Ubuntu
FROM cbcrg/tcoffee:Version_11.00.18778a8

# File Author / Maintainer
MAINTAINER Frederic Lemoine <frederic.lemoine@pasteur.fr>

RUN mkdir /pasteur

ENTRYPOINT ["/opt/tcoffee/bin/t_coffee"]
