# Sratoolkit
# https://hpc.nih.gov/apps/sratoolkit.html
# v3.0.1

FROM ncbi/sra-tools:3.0.1

# File Author / Maintainer
LABEL maintainer="frederic.lemoine@pasteur.fr"

RUN apk update && apk upgrade && apk add bash coreutils
